import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Andreas',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
     {
        name: 'Gucci Women\'s Bag',
        slug: 'gucci-womens-bag',
        category: 'bags',
        image: '/images/p1.jpg',
        price: 120,
        countInStock: 12,
        brand: 'Gucci',
        rating: 2.7,
        numReviews: 721,
        description: 'High-quality bag for women, designed by Gucci.',
      },
      {
        name: 'Gucci Men\'s T-Shirt',
        slug: 'gucci-mens-tshirt',
        category: 'clothing',
        image: '/images/p2.jpg',
        price: 80,
        countInStock: 25,
        brand: 'Gucci',
        rating: 4.5,
        numReviews: 412,
        description: 'Stylish and comfortable t-shirt for men, created by Gucci.',
      },
      {
        name: 'Gucci Women\'s Dress',
        slug: 'gucci-womens-dress',
        category: 'clothing',
        image: '/images/p3.jpg',
        price: 250,
        countInStock: 8,
        brand: 'Gucci',
        rating: 5,
        numReviews: 98,
        description: 'Elegant and fashionable dress for women, crafted by Gucci.',
      },
      {
        name: 'Gucci Men\'s Watch',
        slug: 'gucci-mens-watch',
        category: 'accessories',
        image: '/images/p4.jpg',
        price: 350,
        countInStock: 5,
        brand: 'Gucci',
        rating: 4.6,
        numReviews: 206,
        description: 'Sleek and sophisticated watch for men, designed by Gucci.',
      },
      {
        name: 'Gucci Women\'s Sunglasses',
        slug: 'gucci-womens-sunglasses',
        category: 'accessories',
        image: '/images/p5.jpg',
        price: 200,
        countInStock: 15,
        brand: 'Gucci',
        rating: 3.8,
        numReviews: 304,
        description: 'Trendy and stylish sunglasses for women, created by Gucci.',
      },
    ],
  };
  
  export default data;